version: '3.9'
services:
    nginx:
        build: nginx
        container_name: nginx
        ports:
            - ${NGNIX_PORT}:80
        depends_on:
            - php8.2-fpm
            - php8.1-fpm
            - phpmyadmin
        links:
            - php8.2-fpm
            - php8.1-fpm
            - phpmyadmin
        volumes:
            - './nginx/vhosts/:/etc/nginx/conf.d/'
            - ${DOCKER_VOLUME_PATH}:/var/www
            - '${PATH_LOG_NGINX}:/var/log/nginx'
        networks:
            fidel_net:
                ipv4_address: 172.16.238.10
                ipv6_address: 2001:3984:3989::10
        restart: always

    php8.2-fpm:
        build: php8.2-custom
        container_name: php8.2-fpm
        extra_hosts:
            - "mail:172.16.238.16"
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ${SSH_PATH}:/root/.ssh/
            - ./tools/php8.2/php.ini:/usr/local/etc/php/php.ini-development
        depends_on:
            - mariadb
        networks:
            fidel_net:
                ipv4_address: 172.16.238.11
                ipv6_address: 2001:3984:3989::11
        restart: always

    php8.1-fpm:
        build: php8.1-custom
        container_name: php8.1-fpm
        extra_hosts:
            - "mail:172.16.238.16"
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
#            - /mnt/mmnas/files/:/mnt/mmnas/files/
            - ${SSH_PATH}:/root/.ssh/
            - ./tools/php8.1/php.ini:/usr/local/etc/php/php.ini-development
        depends_on:
            - mariadb
#            - redis
        networks:
            fidel_net:
                ipv4_address: 172.16.238.12
                ipv6_address: 2001:3984:3989::12
        restart: always

    mariadb:
        image: mariadb
        container_name: mariadb
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hub
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - db-volume:/var/lib/mysql
            - ${DOCKER_VOLUME_PATH}:/var/www
        networks:
            fidel_net:
                ipv4_address: 172.16.238.13
                ipv6_address: 2001:3984:3989::13
        restart: always

#    redis:
#        image: redis:alpine
#        ports:
#            - ${REDIS_PORT}:6379
#        networks:
#            fidel_net:
#                ipv4_address: 172.16.238.--
#                ipv6_address: 2001:3984:3989::--
#        restart: always

    memcached:
        image: memcached:alpine
        container_name: memcached
        ports:
            - 11212:11212
        networks:
            fidel_net:
                ipv4_address: 172.16.238.14
                ipv6_address: 2001:3984:3989::14
        restart: always

    tools:
        build: tools
        container_name: tools
        extra_hosts:
            - "mail:172.16.238.16"
        environment:
            - GIT_NAME=${GIT_NAME}
            - GIT_EMAIL=${GIT_EMAIL}
            - GIT_HOST=stash.myapplication.fr
            - GIT_IP=217.174.201.232
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ${SSH_PATH}:/root/.ssh/
        networks:
            fidel_net:
                ipv4_address: 172.16.238.15
                ipv6_address: 2001:3984:3989::15
        restart: always
        command: "tail -f /dev/null"

    # Mailer : configure smtp with MAILER_DSN=smtp://mail:1025 and open browser on 8025
    # http://127.0.0.1:8025/#
    mail:
        image: mailhog/mailhog
        container_name: mail
        networks:
            fidel_net:
                ipv4_address: 172.16.238.16
                ipv6_address: 2001:3984:3989::16
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: always

    # Uncomment if you want to use PHPMYADMIN root root
    # http://phpmyadmin.localhost:8088/index.php?route=/&route=%2F
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8088:80"
        restart: always
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=root
            - MEMORY_LIMIT=2G
            - UPLOAD_LIMIT=2G
        networks:
            fidel_net:
                ipv4_address: 172.16.238.17
                ipv6_address: 2001:3984:3989::17

#    angular-app:
#        image: node:14
#        container_name: angular
#        working_dir: /app
#        volumes:
#            - ${DOCKER_VOLUME_PATH}/angular-app:/app
#        command: >
#            sh -c "npm install && ng serve --host 0.0.0.0 --disable-host-check"
#        networks:
#            fidel_net:
#                ipv4_address: 172.16.238.--
#                ipv6_address: 2001:3984:3989::--

networks:
    fidel_net:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
                - subnet: "2001:3984:3989::/64"

volumes:
    db-volume:
    config-volume:
#     es-volume:#    graylog-config-volume:
#    graylog-journal-volume: