version: '3.9'
services:
    nginx:
        build: nginx
        ports:
            - ${NGNIX_PORT}:80
        depends_on:
            - php7.4-fpm
            - php8.0-fpm
            - php8.1-fpm
        links:
            - php7.4-fpm
            - php8.0-fpm
            - php8.1-fpm
        volumes:
            - './nginx/vhosts/:/etc/nginx/conf.d/'
            - ${DOCKER_VOLUME_PATH}:/var/www
            - '${PATH_LOG_NGINX}:/var/log/nginx'
        networks:
            fidel_net:
                ipv4_address: 172.16.238.10
                ipv6_address: 2001:3984:3989::10
        restart: always

    php7.4-fpm:
        build: php7.4-custom
        extra_hosts:
            - "mail:172.16.238.17"
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
#            - /mnt/mmnas/files/:/mnt/mmnas/files/
            - ${SSH_PATH}:/root/.ssh/
        depends_on:
            - db
#            - redis
        networks:
            fidel_net:
                ipv4_address: 172.16.238.11
                ipv6_address: 2001:3984:3989::11
        restart: always

    php8.0-fpm:
        build: php8.0-custom
        extra_hosts:
            - "mail:172.16.238.17"
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ${SSH_PATH}:/root/.ssh/
            - ./tools/php8.0/php.ini:/usr/local/etc/php/php.ini-development
        depends_on:
            - db
        networks:
            fidel_net:
                ipv4_address: 172.16.238.19
                ipv6_address: 2001:3984:3989::19
        restart: always

    php8.1-fpm:
        build: php8.1-custom
        extra_hosts:
            - "mail:172.16.238.17"
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
#            - /mnt/mmnas/files/:/mnt/mmnas/files/
            - ${SSH_PATH}:/root/.ssh/
            - ./tools/php8.1/php.ini:/usr/local/etc/php/php.ini-development
        depends_on:
            - db
#            - redis
        networks:
            fidel_net:
                ipv4_address: 172.16.238.12
                ipv6_address: 2001:3984:3989::12
        restart: always

    db:
        image: mariadb
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hub
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - db-volume:/var/lib/mysql
            - ${DOCKER_VOLUME_PATH}:/var/www
        networks:
            fidel_net:
                ipv4_address: 172.16.238.13
                ipv6_address: 2001:3984:3989::13
        restart: always

#    redis:
#        image: redis:alpine
#        ports:
#            - ${REDIS_PORT}:6379
#        networks:
#            fidel_net:
#                ipv4_address: 172.16.238.14
#                ipv6_address: 2001:3984:3989::14
#        restart: always

    memcached:
        image: memcached:alpine
        ports:
            - 11212:11212
        networks:
            fidel_net:
                ipv4_address: 172.16.238.15
                ipv6_address: 2001:3984:3989::15
        restart: always

    tools:
        build: tools
        extra_hosts:
            - "mail:172.16.238.17"
        environment:
            - GIT_NAME=${GIT_NAME}
            - GIT_EMAIL=${GIT_EMAIL}
            - GIT_HOST=stash.manymore.fr
            - GIT_IP=217.174.201.232
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ${SSH_PATH}:/root/.ssh/
        networks:
            fidel_net:
                ipv4_address: 172.16.238.16
                ipv6_address: 2001:3984:3989::16
        restart: always
        command: "tail -f /dev/null"

    # Mailer : configure smtp with MAILER_DSN=smtp://mail:1025 and open browser on 8025
    mail:
        image: mailhog/mailhog
        networks:
            fidel_net:
                ipv4_address: 172.16.238.17
                ipv6_address: 2001:3984:3989::17
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: always

# Uncomment if you want to use PHPMYADMIN
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8088:80"
        restart: always
        environment:
            - PMA_HOST=db
            - MEMORY_LIMIT=2G
            - UPLOAD_LIMIT=2G
        depends_on:
          - nginx
        networks:
            fidel_net:
                ipv4_address: 172.16.238.18
                ipv6_address: 2001:3984:3989::18

networks:
    fidel_net:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
                - subnet: "2001:3984:3989::/64"

volumes:
    db-volume:
    config-volume:
#     es-volume:#    graylog-config-volume:
#    graylog-journal-volume: